#include "EXRAILMacros.h"

ROSTER(5,"A4 William Whitehall","///F3 Shunting")
ROSTER(6,"DB Schenker Class 08","///F3 Shunting")
ROSTER(7,"Duchess of Montrose",
  "/F1 Background/*F2 Whistle 1/*F3 Whistle 2/*F4 Brake/F5 Cylinder Cock/*F6 Wheel Slip/F7 Coal Shoveling/F8 Injector/F9 Safety Valve/*F10 Guards Whistle/*F11 Coupling/*F12 Carrage Brake Squeal/F13 Flange Squeal/F14 Blower/*F15 Slam Doors/F16 Firemans Breakfast/F17 Blowdown/*F18 Coal Pusher/F19 Water Fill/F20 Chuffing Coasting/////F25 Shunting Mode/F26 Creep Mode/F27 Apply Brake/F28 Auto Function Play"
)

ALIAS(SEQUENCE_STARTUP)


// This is the startup sequence, 
AUTOSTART
  START(SEQUENCE_STARTUP)    
DONE 

// point alias pins
ALIAS(POINT_FRONT_RIGHT_CROSS_OUTER_PIN    , 100)
ALIAS(POINT_FRONT_RIGHT_REVERSE_LOOP_PIN   , 101)
ALIAS(POINT_FRONT_RIGHT_LOOP_PIN           , 102)
ALIAS(POINT_ENGINE_SHED_PIN                , 103)
ALIAS(POINT_YARD_PIN                       , 104)
ALIAS(POINT_FRONT_RIGHT_CROSS_INNER_PIN    , 105)
ALIAS(POINT_FRONT_LEFT_CROSS_OUTER_PIN     , 120)
ALIAS(POINT_FRONT_LEFT_LOOP_PIN            , 121)
ALIAS(POINT_BACK_LEFT_CROSS_OUTER_PIN      , 122)
ALIAS(POINT_BACK_LEFT_REVERSE_LOOP_PIN     , 123)
ALIAS(POINT_GOODS_OR_PASSENGER_PIN         , 124)
ALIAS(POINT_PASSENGER_SIDINGS_PIN          , 125)
ALIAS(POINT_GOODS_SHED_PIN                 , 126)
ALIAS(POINT_GOODS_SIDINGS_PIN              , 127)
ALIAS(POINT_FRONT_LEFT_CROSS_INNER_PIN     , 128)
ALIAS(POINT_BACK_LEFT_CROSS_INNER_PIN      , 129)

// point alias
ALIAS(POINT_FRONT_RIGHT_CROSS_OUTER)
ALIAS(POINT_FRONT_RIGHT_REVERSE_LOOP)
ALIAS(POINT_FRONT_RIGHT_LOOP)
ALIAS(POINT_ENGINE_SHED)
ALIAS(POINT_YARD)
ALIAS(POINT_FRONT_RIGHT_CROSS_INNER)
ALIAS(POINT_FRONT_LEFT_CROSS_OUTER)
ALIAS(POINT_FRONT_LEFT_LOOP)
ALIAS(POINT_BACK_LEFT_CROSS_OUTER)
ALIAS(POINT_BACK_LEFT_REVERSE_LOOP)
ALIAS(POINT_GOODS_OR_PASSENGER)
ALIAS(POINT_PASSENGER_SIDINGS)
ALIAS(POINT_GOODS_SHED)
ALIAS(POINT_GOODS_SIDINGS)
ALIAS(POINT_FRONT_LEFT_CROSS_INNER)
ALIAS(POINT_BACK_LEFT_CROSS_INNER)
ALIAS(POINT_FRONT_RIGHT_CROSSOVER)
ALIAS(POINT_FRONT_LEFT_CROSSOVER)
ALIAS(POINT_BACK_LEFT_CROSSOVER)

// uncoupler alias pins
ALIAS(UNCOUPLER_FRONT_RIGHT_OUTER_PIN, 108)
ALIAS(UNCOUPLER_FRONT_RIGHT_INNER_PIN, 109)
ALIAS(UNCOUPLER_FRONT_RIGHT_LOOP_PIN , 140)

ALIAS(UNCOUPLER_FRONT_LEFT_OUTER_PIN , 141)
ALIAS(UNCOUPLER_FRONT_LEFT_INNER_PIN , 142)
ALIAS(UNCOUPLER_FRONT_LEFT_LOOP_PIN  , 143)
ALIAS(UNCOUPLER_PASSENGER_REAR_PIN   , 144)
ALIAS(UNCOUPLER_PASSENGER_FRONT_PIN  , 145)
ALIAS(UNCOUPLER_GOODS_SHED_PIN       , 146)
ALIAS(UNCOUPLER_GOODS_BACK_PIN       , 147)
ALIAS(UNCOUPLER_GOODS_FRONT_PIN      , 148)

// uncoupler alias
ALIAS(UNCOUPLER_FRONT_RIGHT_OUTER)
ALIAS(UNCOUPLER_FRONT_RIGHT_INNER)
ALIAS(UNCOUPLER_FRONT_RIGHT_LOOP)

ALIAS(UNCOUPLER_FRONT_LEFT_OUTER)
ALIAS(UNCOUPLER_FRONT_LEFT_INNER)
ALIAS(UNCOUPLER_FRONT_LEFT_LOOP)

ALIAS(UNCOUPLER_PASSENGER_REAR)
ALIAS(UNCOUPLER_PASSENGER_FRONT)
ALIAS(UNCOUPLER_GOODS_SHED)
ALIAS(UNCOUPLER_GOODS_BACK)
ALIAS(UNCOUPLER_GOODS_FRONT)

//button alias
ALIAS(BUTTON_KILL                                , 300)
ALIAS(BUTTON_POINT_BACK_LEFT_CROSSOVER           , 301)
ALIAS(BUTTON_POINT_BACK_LEFT_REVERSE_LOOP        , 302)
ALIAS(BUTTON_UNCOUPLE_BACK_SIDING                , 303)
ALIAS(BUTTON_UNCOUPLE_GOODS_SHED                 , 304)
ALIAS(BUTTON_BACK_LEFT_GOODS_SIDINGS             , 305)
ALIAS(BUTTON_UNCOUPLE_FRONT_SIDING               , 306)
ALIAS(BUTTON_POINT_FRONT_LEFT_LOOP               , 307)
ALIAS(BUTTON_POINT_FRONT_LEFT_CROSSOVER          , 308)
ALIAS(BUTTON_UNCOUPLE_OUTER_LEFT                 , 309)
ALIAS(BUTTON_UNCOUPLE_INNER_LEFT                 , 310)
ALIAS(BUTTON_UNCOUPLE_LEFT_LOOP                  , 311)
ALIAS(BUTTON_POINT_GOODS_SHED                    , 312)
ALIAS(BUTTON_UNCOUPLE_FRONT_PASSENGER            , 313)
ALIAS(BUTTON_UNCOUPLE_REAR_PASSENGER             , 314)
ALIAS(BUTTON_POINT_PASSENGER_SIDINGS             , 315)


ALIAS(BUTTON_POINT_GOODS_OR_PASSENGER            , 320)
ALIAS(BUTTON_POINT_YARD                          , 321)
ALIAS(BUTTON_UNCOUPLE_RIGHT_LOOP                 , 322)
ALIAS(BUTTON_UNCOUPLE_INNER_RIGHT                , 323)
ALIAS(BUTTON_POINT_ENGINE_SHED                   , 324)
ALIAS(BUTTON_POINT_FRONT_RIGHT_LOOP              , 325)
ALIAS(BUTTON_UNCOUPLE_OUTER_RIGHT                , 326)
ALIAS(BUTTON_POINT_FRONT_RIGHT_CROSSOVER         , 327)
ALIAS(BUTTON_POINT_FRONT_RIGHT_REVERSE_LOOP      , 328)


// sensor pins
ALIAS(SENSOR_RIGHT_OUTER_CURVE                   , 223)
ALIAS(SENSOR_RIGHT_INNER_CURVE                   , 224)
ALIAS(SENSOR_REVERSE_LOOP                        , 208)
ALIAS(SENSOR_OCCUPIED_FRONT_OUTER_1              , 202)
ALIAS(SENSOR_OCCUPIED_FRONT_OUTER_2              , 222)
ALIAS(SENSOR_OCCUPIED_FRONT_INNER_1              , 201)
ALIAS(SENSOR_OCCUPIED_FRONT_INNER_2              , 221)
ALIAS(SENSOR_OCCUPIED_LOOP_1                     , 200)
ALIAS(SENSOR_OCCUPIED_LOOP_2                     , 220)
ALIAS(SENSOR_OCCUPIED_REAR_OUTER_1               , 207)
ALIAS(SENSOR_OCCUPIED_REAR_OUTER_2               , 226)
ALIAS(SENSOR_OCCUPIED_REAR_INNER_1               , 206)
ALIAS(SENSOR_OCCUPIED_REAR_INNER_2               , 225)
ALIAS(SENSOR_OCCUPIED_YARD                       , 205)
ALIAS(SENSOR_LEFT_INNER_CURVE                    , 203)
ALIAS(SENSOR_LEFT_OUTER_CURVE                    , 204)

// JMRI_SENSOR(200,9)
// JMRI_SENSOR(220,7)


// points
// "Front Right Crossover Outer"
SERVO_TURNOUT(POINT_FRONT_RIGHT_CROSS_OUTER , POINT_FRONT_RIGHT_CROSS_OUTER_PIN , 300, 350, Instant, HIDDEN)
SERVO_TURNOUT(POINT_FRONT_RIGHT_REVERSE_LOOP, POINT_FRONT_RIGHT_REVERSE_LOOP_PIN, 300, 360, Instant, "Front Right Reverse Loop")
SERVO_TURNOUT(POINT_FRONT_RIGHT_LOOP        , POINT_FRONT_RIGHT_LOOP_PIN        , 280, 320, Instant, "Front Right Loop")
SERVO_TURNOUT(POINT_ENGINE_SHED             , POINT_ENGINE_SHED_PIN             , 350, 300, Instant, "To Engine Shed")
SERVO_TURNOUT(POINT_YARD                    , POINT_YARD_PIN                    , 300, 360, Instant, "To Yard")
// "Front Right Crossover Inner"
SERVO_TURNOUT(POINT_FRONT_RIGHT_CROSS_INNER , POINT_FRONT_RIGHT_CROSS_INNER_PIN , 270, 310, Instant, HIDDEN)
// "Front Left Crossover Outer"
SERVO_TURNOUT(POINT_FRONT_LEFT_CROSS_OUTER  , POINT_FRONT_LEFT_CROSS_OUTER_PIN  , 375, 300, Instant, HIDDEN)
SERVO_TURNOUT(POINT_FRONT_LEFT_LOOP         , POINT_FRONT_LEFT_LOOP_PIN         , 360, 300, Instant, "Front Left Loop")
// "Back Left Crossover Outer"
SERVO_TURNOUT(POINT_BACK_LEFT_CROSS_OUTER   , POINT_BACK_LEFT_CROSS_OUTER_PIN   , 230, 300, Instant, HIDDEN)
SERVO_TURNOUT(POINT_BACK_LEFT_REVERSE_LOOP  , POINT_BACK_LEFT_REVERSE_LOOP_PIN  , 230, 300, Instant, "Back Left Reverse Loop")

SERVO_TURNOUT(POINT_GOODS_OR_PASSENGER      , POINT_GOODS_OR_PASSENGER_PIN      , 250, 300, Instant, "Goods or Passenger")
SERVO_TURNOUT(POINT_PASSENGER_SIDINGS       , POINT_PASSENGER_SIDINGS_PIN       , 260, 320, Instant, "Passenger Sidings")
SERVO_TURNOUT(POINT_GOODS_SHED              , POINT_GOODS_SHED_PIN              , 250, 300, Instant, "Goods Shed")
SERVO_TURNOUT(POINT_GOODS_SIDINGS           , POINT_GOODS_SIDINGS_PIN           , 250, 300, Instant, "Goods Sidings")

// "Front Left Crossover Inner"
SERVO_TURNOUT(POINT_FRONT_LEFT_CROSS_INNER  , POINT_FRONT_LEFT_CROSS_INNER_PIN  , 260, 310, Instant, HIDDEN)
// "Back Left Crossover Inner"
SERVO_TURNOUT(POINT_BACK_LEFT_CROSS_INNER   , POINT_BACK_LEFT_CROSS_INNER_PIN   , 260, 310, Instant, HIDDEN)

VIRTUAL_TURNOUT(POINT_FRONT_RIGHT_CROSSOVER, "Front Right Crossover")
VIRTUAL_TURNOUT(POINT_FRONT_LEFT_CROSSOVER , "Front Left Crossover")
VIRTUAL_TURNOUT(POINT_BACK_LEFT_CROSSOVER  , "Back Left Crossover")


// UNCOUPLERS, are defined as servo_turnouts
SERVO_TURNOUT(UNCOUPLER_FRONT_RIGHT_OUTER, UNCOUPLER_FRONT_RIGHT_OUTER_PIN, 260, 300, Instant, "Front Right Outer Uncoupler")
SERVO_TURNOUT(UNCOUPLER_FRONT_RIGHT_INNER, UNCOUPLER_FRONT_RIGHT_INNER_PIN, 250, 300, Instant, "Front Right Inner Uncoupler")
SERVO_TURNOUT(UNCOUPLER_FRONT_RIGHT_LOOP , UNCOUPLER_FRONT_RIGHT_LOOP_PIN , 255, 300, Instant, "Front Right Loop Uncoupler")
SERVO_TURNOUT(UNCOUPLER_FRONT_LEFT_OUTER , UNCOUPLER_FRONT_LEFT_OUTER_PIN , 255, 300, Instant, "Front Left Outer Uncoupler")
SERVO_TURNOUT(UNCOUPLER_FRONT_LEFT_INNER , UNCOUPLER_FRONT_LEFT_INNER_PIN , 250, 300, Instant, "Front Left Inner Uncoupler")
SERVO_TURNOUT(UNCOUPLER_FRONT_LEFT_LOOP  , UNCOUPLER_FRONT_LEFT_LOOP_PIN  , 255, 300, Instant, "Front Left Loop Uncoupler")
SERVO_TURNOUT(UNCOUPLER_PASSENGER_REAR   , UNCOUPLER_PASSENGER_REAR_PIN   , 250, 300, Instant, "Passenger Rear Siding Uncoupler")
SERVO_TURNOUT(UNCOUPLER_PASSENGER_FRONT  , UNCOUPLER_PASSENGER_FRONT_PIN  , 250, 300, Instant, "Passenger Front Siding Uncoupler")
SERVO_TURNOUT(UNCOUPLER_GOODS_SHED       , UNCOUPLER_GOODS_SHED_PIN       , 250, 300, Instant, "Goods Shed Siding Uncoupler")
SERVO_TURNOUT(UNCOUPLER_GOODS_BACK       , UNCOUPLER_GOODS_BACK_PIN       , 250, 300, Instant, "Rear Goods Siding Uncoupler")
SERVO_TURNOUT(UNCOUPLER_GOODS_FRONT      , UNCOUPLER_GOODS_FRONT_PIN      , 250, 300, Instant, "Front Goods Siding Uncoupler")


ALIAS(LED_FRONT_RIGHT_CROSSOVER_CROSSED, 340)
ALIAS(LED_FRONT_RIGHT_CROSSOVER_INNER  , 341)
ALIAS(LED_FRONT_RIGHT_CROSSOVER_OUTER  , 342)
ALIAS(LED_FRONT_RIGHT_REVERSE_LOOP     , 343)
ALIAS(LED_FRONT_RIGHT_LOOP             , 344)
ALIAS(LED_FRONT_RIGHT_LOOP_INNER       , 345)
ALIAS(LED_ENGINE                       , 346)
ALIAS(LED_ENGINE_YARD                  , 347)
ALIAS(LED_YARD                         , 348)
ALIAS(LED_RIGHT_LOOP                   , 349)

ALIAS(LED_OCCUPIED_RIGHT_CURVE_OUTER   , 350)
ALIAS(LED_OCCUPIED_RIGHT_CURVE_INNER   , 351)
ALIAS(LED_OCCUPIED_REVERSE_LOOP        , 352)

ALIAS(LED_UNCOUPLE_FRONT_RIGHT_OUTER   , 353)
ALIAS(LED_UNCOUPLE_FRONT_RIGHT_INNER   , 354)
ALIAS(LED_UNCOUPLE_FRONT_RIGHT_LOOP    , 355)

ALIAS(LED_PASSENGER                    , 360)
ALIAS(LED_GOODS                        , 361)
ALIAS(LED_PASSENGER_FRONT              , 362)
ALIAS(LED_PASSENGER_BACK               , 363)
ALIAS(LED_REAR_REVERSE_LOOP_CLOSED     , 364)
ALIAS(LED_REAR_REVERSE_LOOP_THROWN     , 365)
ALIAS(LED_UNCOUPLE_PASSENGER_FRONT     , 366)
ALIAS(LED_UNCOUPLE_PASSENGER_BACK      , 367)
ALIAS(LED_UNCOUPLE_FRONT_LEFT_OUTER    , 368)
ALIAS(LED_UNCOUPLE_FRONT_LEFT_INNER    , 369)



ALIAS(LED_OCCUPIED_FRONT_OUTER         , 370)
ALIAS(LED_OCCUPIED_FRONT_INNER         , 371)
ALIAS(LED_OCCUPIED_LOOP                , 372)
ALIAS(LED_OCCUPIED_REAR_INNER          , 373)
ALIAS(LED_OCCUPIED_REAR_OUTER          , 374)
ALIAS(LED_OCCUPIED_YARD                , 375)

ALIAS(LED_BACK_LEFT_CROSSOVER_OUTER    , 380)
ALIAS(LED_BACK_LEFT_CROSSOVER_CROSSED  , 381)
ALIAS(LED_BACK_LEFT_CROSSOVER_INNER    , 382)
ALIAS(LED_FRONT_LEFT_CROSSOVER_OUTER   , 383)
ALIAS(LED_FRONT_LEFT_CROSSOVER_CROSSED , 384)
ALIAS(LED_FRONT_LEFT_CROSSOVER_INNER   , 385)
ALIAS(LED_FRONT_LEFT_LOOP              , 386)
ALIAS(LED_GOODS_OR_GOODS_SHED_GOODS    , 387)
ALIAS(LED_GOODS_OR_GOODS_SHED_SHED     , 388)
ALIAS(LED_GOODS_FRONT                  , 389)
ALIAS(LED_GOODS_BACK                   , 390)


ALIAS(LED_UNCOUPLE_FRONT_LEFT_LOOP     , 391)
ALIAS(LED_UNCOUPLE_GOODS_SHED          ,  392)
ALIAS(LED_UNCOUPLE_GOODS_FRONT         , 393)
ALIAS(LED_UNCOUPLE_GOODS_BACK          ,  394)

ALIAS(LED_OCCUPIED_LEFT_CURVE_INNER    , 395)

ALIAS(LED_OCCUPIED_LEFT_CURVE_OUTER    , 400)


// LEDs on mimic
CONFIGURE_SERVO(LED_FRONT_RIGHT_CROSSOVER_CROSSED, 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_RIGHT_CROSSOVER_INNER  , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_RIGHT_CROSSOVER_OUTER  , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_RIGHT_REVERSE_LOOP     , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_RIGHT_LOOP             , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_RIGHT_LOOP_INNER       , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_ENGINE                       , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_ENGINE_YARD                  , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_YARD                         , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_RIGHT_LOOP                   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_PASSENGER                    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_GOODS                        , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_PASSENGER_FRONT              , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_PASSENGER_BACK               , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_REAR_REVERSE_LOOP_CLOSED     , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_REAR_REVERSE_LOOP_THROWN     , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)

CONFIGURE_SERVO(LED_OCCUPIED_RIGHT_CURVE_OUTER   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_RIGHT_CURVE_INNER   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_REVERSE_LOOP        , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_FRONT_OUTER         , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_FRONT_INNER         , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_LOOP                , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_REAR_OUTER          , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_REAR_INNER          , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_YARD                , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)


CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_RIGHT_OUTER   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_RIGHT_INNER   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_RIGHT_LOOP    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)

CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_LEFT_OUTER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_LEFT_INNER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_LEFT_LOOP     , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)

CONFIGURE_SERVO(LED_BACK_LEFT_CROSSOVER_OUTER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_BACK_LEFT_CROSSOVER_CROSSED  , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_BACK_LEFT_CROSSOVER_INNER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_LEFT_CROSSOVER_OUTER   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_LEFT_CROSSOVER_CROSSED , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_LEFT_CROSSOVER_INNER   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_LEFT_LOOP              , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_GOODS_OR_GOODS_SHED_SHED     , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_GOODS_OR_GOODS_SHED_GOODS    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_GOODS_FRONT                  , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_GOODS_BACK                   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)

CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_LEFT_INNER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_GOODS_SHED          , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_GOODS_FRONT         , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_GOODS_BACK          , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)

CONFIGURE_SERVO(LED_OCCUPIED_LEFT_CURVE_INNER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)

CONFIGURE_SERVO(LED_OCCUPIED_LEFT_CURVE_OUTER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)


ONTHROW(POINT_FRONT_RIGHT_CROSSOVER)
  THROW(POINT_FRONT_RIGHT_CROSS_OUTER)
  THROW(POINT_FRONT_RIGHT_CROSS_INNER)
DONE

ONCLOSE(POINT_FRONT_RIGHT_CROSSOVER)
  CLOSE(POINT_FRONT_RIGHT_CROSS_OUTER)
  CLOSE(POINT_FRONT_RIGHT_CROSS_INNER)
DONE

ONTHROW(POINT_FRONT_LEFT_CROSSOVER)
  THROW(POINT_FRONT_LEFT_CROSS_OUTER)
  THROW(POINT_FRONT_LEFT_CROSS_INNER)
DONE

ONCLOSE(POINT_FRONT_LEFT_CROSSOVER)
  CLOSE(POINT_FRONT_LEFT_CROSS_OUTER)
  CLOSE(POINT_FRONT_LEFT_CROSS_INNER)
DONE

ONTHROW(POINT_BACK_LEFT_CROSSOVER)
  THROW(POINT_BACK_LEFT_CROSS_OUTER)
  THROW(POINT_BACK_LEFT_CROSS_INNER)
DONE

ONCLOSE(POINT_BACK_LEFT_CROSSOVER)
  CLOSE(POINT_BACK_LEFT_CROSS_OUTER)
  CLOSE(POINT_BACK_LEFT_CROSS_INNER)
DONE


ONTHROW(POINT_FRONT_RIGHT_REVERSE_LOOP)
  SET(LED_FRONT_RIGHT_REVERSE_LOOP)
  RESET(LED_FRONT_RIGHT_CROSSOVER_INNER)
DONE

ONCLOSE(POINT_FRONT_RIGHT_REVERSE_LOOP)
  RESET(LED_FRONT_RIGHT_REVERSE_LOOP)
  IFCLOSED(POINT_FRONT_RIGHT_CROSSOVER)
    SET(LED_FRONT_RIGHT_CROSSOVER_INNER)
  ENDIF
DONE

ONTHROW(POINT_FRONT_RIGHT_LOOP)
  SET(LED_FRONT_RIGHT_LOOP)
  RESET(LED_FRONT_RIGHT_LOOP_INNER)
DONE

ONCLOSE(POINT_FRONT_RIGHT_LOOP)
  SET(LED_FRONT_RIGHT_LOOP_INNER)
  RESET(LED_FRONT_RIGHT_LOOP)
DONE

ONTHROW(POINT_ENGINE_SHED)
  SET(LED_ENGINE)
  RESET(LED_ENGINE_YARD)
DONE

ONCLOSE(POINT_ENGINE_SHED)
  SET(LED_ENGINE_YARD)
  RESET(LED_ENGINE)
DONE

ONTHROW(POINT_YARD)
  SET(LED_YARD)
  RESET(LED_RIGHT_LOOP)
DONE

ONCLOSE(POINT_YARD)
  SET(LED_RIGHT_LOOP)
  RESET(LED_YARD)
DONE

ONTHROW(POINT_GOODS_OR_PASSENGER)
  SET(LED_PASSENGER)
  RESET(LED_GOODS)
DONE

ONCLOSE(POINT_GOODS_OR_PASSENGER)
  SET(LED_GOODS)
  RESET(LED_PASSENGER)
DONE


ONTHROW(POINT_PASSENGER_SIDINGS)
  SET(LED_PASSENGER_BACK)
  RESET(LED_PASSENGER_FRONT)
DONE

ONCLOSE(POINT_PASSENGER_SIDINGS)
  SET(LED_PASSENGER_FRONT)
  RESET(LED_PASSENGER_BACK)
DONE

ONTHROW(POINT_GOODS_SHED)
  SET(LED_GOODS_OR_GOODS_SHED_SHED)
  RESET(LED_GOODS_OR_GOODS_SHED_GOODS)

DONE

ONCLOSE(POINT_GOODS_SHED)
  SET(LED_GOODS_OR_GOODS_SHED_GOODS)
  RESET(LED_GOODS_OR_GOODS_SHED_SHED)
DONE


ONTHROW(POINT_GOODS_SIDINGS)
  SET(LED_GOODS_BACK)
  RESET(LED_GOODS_FRONT)
DONE

ONCLOSE(POINT_GOODS_SIDINGS)
  SET(LED_GOODS_FRONT)
  RESET(LED_GOODS_BACK)
DONE

ONTHROW(POINT_BACK_LEFT_REVERSE_LOOP)
  SET(LED_REAR_REVERSE_LOOP_THROWN)
  RESET(LED_REAR_REVERSE_LOOP_CLOSED)
DONE

ONCLOSE(POINT_BACK_LEFT_REVERSE_LOOP)
  SET(LED_REAR_REVERSE_LOOP_CLOSED)
  RESET(LED_REAR_REVERSE_LOOP_THROWN)
DONE

ONTHROW(POINT_FRONT_RIGHT_CROSSOVER)
  SET(LED_FRONT_RIGHT_CROSSOVER_CROSSED)
  RESET(LED_FRONT_RIGHT_CROSSOVER_INNER)
DONE

ONCLOSE(POINT_FRONT_RIGHT_CROSSOVER)
  RESET(LED_FRONT_RIGHT_CROSSOVER_CROSSED)
  IFCLOSED(POINT_FRONT_LEFT_CROSS_OUTER)
    SET(LED_FRONT_LEFT_CROSSOVER_INNER)
  ENDIF
DONE


ONTHROW(POINT_BACK_LEFT_CROSSOVER)
  RESET(LED_BACK_LEFT_CROSSOVER_OUTER)
  SET(LED_BACK_LEFT_CROSSOVER_CROSSED)
  RESET(LED_BACK_LEFT_CROSSOVER_INNER)
DONE

ONCLOSE(POINT_BACK_LEFT_CROSSOVER)
  SET(LED_BACK_LEFT_CROSSOVER_OUTER)
  RESET(LED_BACK_LEFT_CROSSOVER_CROSSED)
  SET(LED_BACK_LEFT_CROSSOVER_INNER)
DONE

ONTHROW(POINT_FRONT_LEFT_CROSSOVER)
  RESET(LED_FRONT_LEFT_CROSSOVER_OUTER)
  SET(LED_FRONT_LEFT_CROSSOVER_CROSSED)
  RESET(LED_FRONT_LEFT_CROSSOVER_INNER)
DONE

ONCLOSE(POINT_FRONT_LEFT_CROSSOVER)
  SET(LED_FRONT_LEFT_CROSSOVER_OUTER)
  RESET(LED_FRONT_LEFT_CROSSOVER_CROSSED)
  IFCLOSED(POINT_FRONT_LEFT_LOOP)
    SET(LED_FRONT_LEFT_CROSSOVER_INNER)
  ENDIF
DONE

ONTHROW(POINT_FRONT_LEFT_LOOP)
  SET(LED_FRONT_LEFT_LOOP)
  RESET(LED_FRONT_LEFT_CROSSOVER_INNER)
  IFCLOSED(POINT_FRONT_LEFT_CROSS_INNER)
    SET(LED_FRONT_LEFT_CROSSOVER_INNER)
  ENDIF
DONE

ONCLOSE(POINT_FRONT_LEFT_LOOP)
  RESET(LED_FRONT_LEFT_LOOP)
  IFCLOSED(POINT_FRONT_LEFT_CROSS_INNER)
    SET(LED_FRONT_LEFT_CROSSOVER_INNER)
  ENDIF
DONE

// UNCOUPLERS

ONTHROW(UNCOUPLER_FRONT_RIGHT_OUTER)
  SET(LED_UNCOUPLE_FRONT_RIGHT_OUTER)
DONE

ONCLOSE(UNCOUPLER_FRONT_RIGHT_OUTER)
  RESET(LED_UNCOUPLE_FRONT_RIGHT_OUTER)
DONE

ONTHROW(UNCOUPLER_FRONT_RIGHT_INNER)
  SET(LED_UNCOUPLE_FRONT_RIGHT_INNER)
DONE

ONCLOSE(UNCOUPLER_FRONT_RIGHT_INNER)
  RESET(LED_UNCOUPLE_FRONT_RIGHT_INNER)
DONE

ONTHROW(UNCOUPLER_FRONT_RIGHT_LOOP)
  SET(LED_UNCOUPLE_FRONT_RIGHT_LOOP)
DONE

ONCLOSE(UNCOUPLER_FRONT_RIGHT_LOOP)
  RESET(LED_UNCOUPLE_FRONT_RIGHT_LOOP)
DONE

ONTHROW(UNCOUPLER_FRONT_LEFT_OUTER)
  SET(LED_UNCOUPLE_FRONT_LEFT_OUTER)
DONE

ONCLOSE(UNCOUPLER_FRONT_LEFT_OUTER)
  RESET(LED_UNCOUPLE_FRONT_LEFT_OUTER)
DONE

ONTHROW(UNCOUPLER_FRONT_LEFT_INNER)
  SET(LED_UNCOUPLE_FRONT_LEFT_INNER)
DONE

ONCLOSE(UNCOUPLER_FRONT_LEFT_INNER)
  RESET(LED_UNCOUPLE_FRONT_LEFT_INNER)
DONE

ONTHROW(UNCOUPLER_FRONT_LEFT_LOOP)
  SET(LED_UNCOUPLE_FRONT_LEFT_LOOP)
DONE

ONCLOSE(UNCOUPLER_FRONT_LEFT_LOOP)
  RESET(LED_UNCOUPLE_FRONT_LEFT_LOOP)
DONE

ONTHROW(UNCOUPLER_PASSENGER_REAR)
  SET(LED_UNCOUPLE_PASSENGER_BACK)
DONE

ONCLOSE(UNCOUPLER_PASSENGER_REAR)
  RESET(LED_UNCOUPLE_PASSENGER_BACK)
DONE

ONTHROW(UNCOUPLER_PASSENGER_FRONT)
  SET(LED_UNCOUPLE_PASSENGER_FRONT)
DONE

ONCLOSE(UNCOUPLER_PASSENGER_FRONT)
  RESET(LED_UNCOUPLE_PASSENGER_FRONT)
DONE

ONTHROW(UNCOUPLER_GOODS_SHED)
  SET(LED_UNCOUPLE_GOODS_SHED)
DONE

ONCLOSE(UNCOUPLER_GOODS_SHED)
  RESET(LED_UNCOUPLE_GOODS_SHED)
DONE

ONTHROW(UNCOUPLER_GOODS_BACK)
  SET(LED_UNCOUPLE_GOODS_BACK)
DONE

ONCLOSE(UNCOUPLER_GOODS_BACK)
  RESET(LED_UNCOUPLE_GOODS_BACK)
DONE

ONTHROW(UNCOUPLER_GOODS_FRONT)
  SET(LED_UNCOUPLE_GOODS_FRONT)
DONE

ONCLOSE(UNCOUPLER_GOODS_FRONT)
  RESET(LED_UNCOUPLE_GOODS_FRONT)
DONE




// Kill!!
ONBUTTON(BUTTON_KILL)
  POWEROFF
  KILLALL
DONE

// back left crossover
ONBUTTON(BUTTON_POINT_BACK_LEFT_CROSSOVER)
  TOGGLE_TURNOUT(POINT_BACK_LEFT_CROSSOVER)
DONE

// back left reverse loop
ONBUTTON(BUTTON_POINT_BACK_LEFT_REVERSE_LOOP)
  TOGGLE_TURNOUT(POINT_BACK_LEFT_REVERSE_LOOP)
DONE

// goods sidings
ONBUTTON(BUTTON_BACK_LEFT_GOODS_SIDINGS)
  TOGGLE_TURNOUT(POINT_GOODS_SIDINGS)
DONE

// front left loop
ONBUTTON(BUTTON_POINT_FRONT_LEFT_LOOP)
  TOGGLE_TURNOUT(POINT_FRONT_LEFT_LOOP)
DONE

// front left crossover
ONBUTTON(BUTTON_POINT_FRONT_LEFT_CROSSOVER)
  TOGGLE_TURNOUT(POINT_FRONT_LEFT_CROSSOVER)
DONE


// goods shed
ONBUTTON(BUTTON_POINT_GOODS_SHED)
  TOGGLE_TURNOUT(POINT_GOODS_SHED)
DONE


// passenger sidings
ONBUTTON(BUTTON_POINT_PASSENGER_SIDINGS)
  TOGGLE_TURNOUT(POINT_PASSENGER_SIDINGS)
DONE


ONBUTTON(BUTTON_POINT_GOODS_OR_PASSENGER)
  TOGGLE_TURNOUT(POINT_GOODS_OR_PASSENGER)
DONE

ONBUTTON(BUTTON_POINT_YARD)
  TOGGLE_TURNOUT(POINT_YARD)
DONE

ONBUTTON(BUTTON_POINT_ENGINE_SHED)
  TOGGLE_TURNOUT(POINT_ENGINE_SHED)
DONE

ONBUTTON(BUTTON_POINT_FRONT_RIGHT_LOOP)
  TOGGLE_TURNOUT(POINT_FRONT_RIGHT_LOOP)
DONE

ONBUTTON(BUTTON_POINT_FRONT_RIGHT_CROSSOVER)
  TOGGLE_TURNOUT(POINT_FRONT_RIGHT_CROSSOVER)
DONE

ONBUTTON(BUTTON_POINT_FRONT_RIGHT_REVERSE_LOOP)
  TOGGLE_TURNOUT(POINT_FRONT_RIGHT_REVERSE_LOOP)
DONE

// UNCOUPLERS

ONBUTTON(BUTTON_UNCOUPLE_OUTER_RIGHT)
  TOGGLE_TURNOUT(UNCOUPLER_FRONT_RIGHT_OUTER)
DONE

ONBUTTON(BUTTON_UNCOUPLE_INNER_RIGHT)
  TOGGLE_TURNOUT(UNCOUPLER_FRONT_RIGHT_INNER)
DONE

ONBUTTON(BUTTON_UNCOUPLE_RIGHT_LOOP)
  TOGGLE_TURNOUT(UNCOUPLER_FRONT_RIGHT_LOOP)
DONE

ONBUTTON(BUTTON_UNCOUPLE_OUTER_LEFT)
  TOGGLE_TURNOUT(UNCOUPLER_FRONT_LEFT_OUTER)
DONE

ONBUTTON(BUTTON_UNCOUPLE_INNER_LEFT)
  TOGGLE_TURNOUT(UNCOUPLER_FRONT_LEFT_INNER)
DONE

ONBUTTON(BUTTON_UNCOUPLE_LEFT_LOOP)
  TOGGLE_TURNOUT(UNCOUPLER_FRONT_LEFT_LOOP)
DONE

ONBUTTON(BUTTON_UNCOUPLE_REAR_PASSENGER)
  TOGGLE_TURNOUT(UNCOUPLER_PASSENGER_REAR)
DONE

ONBUTTON(BUTTON_UNCOUPLE_FRONT_PASSENGER)
  TOGGLE_TURNOUT(UNCOUPLER_PASSENGER_FRONT)
DONE

ONBUTTON(BUTTON_UNCOUPLE_GOODS_SHED)
  TOGGLE_TURNOUT(UNCOUPLER_GOODS_SHED)
DONE

ONBUTTON(BUTTON_UNCOUPLE_BACK_SIDING)
  TOGGLE_TURNOUT(UNCOUPLER_GOODS_BACK)
DONE

ONBUTTON(BUTTON_UNCOUPLE_FRONT_SIDING)
  TOGGLE_TURNOUT(UNCOUPLER_GOODS_FRONT)
DONE

// sensors
ONSENSOR(-SENSOR_RIGHT_OUTER_CURVE)
  IF(-SENSOR_RIGHT_OUTER_CURVE)
    SET(LED_OCCUPIED_RIGHT_CURVE_OUTER)
  ELSE
    RESET(LED_OCCUPIED_RIGHT_CURVE_OUTER)
  ENDIF
DONE

ONSENSOR(-SENSOR_RIGHT_INNER_CURVE)
  IF(-SENSOR_RIGHT_INNER_CURVE)
    SET(LED_OCCUPIED_RIGHT_CURVE_INNER)
  ELSE
    RESET(LED_OCCUPIED_RIGHT_CURVE_INNER)
  ENDIF
DONE

ONSENSOR(-SENSOR_REVERSE_LOOP)
  IF(-SENSOR_REVERSE_LOOP)
    SET(LED_OCCUPIED_REVERSE_LOOP)
  ELSE
    RESET(LED_OCCUPIED_REVERSE_LOOP)
  ENDIF
DONE

ONSENSOR(-SENSOR_OCCUPIED_FRONT_OUTER_1)
  IF(-SENSOR_OCCUPIED_FRONT_OUTER_1)
    SET(LED_OCCUPIED_FRONT_OUTER)
  ELSE 
    IFNOT(-SENSOR_OCCUPIED_FRONT_OUTER_2)
      RESET(LED_OCCUPIED_FRONT_OUTER)
    ENDIF
  ENDIF
DONE

ONSENSOR(-SENSOR_OCCUPIED_FRONT_OUTER_2)
  IF(-SENSOR_OCCUPIED_FRONT_OUTER_2)
    SET(LED_OCCUPIED_FRONT_OUTER)
  ELSE 
    IFNOT(-SENSOR_OCCUPIED_FRONT_OUTER_1)
      RESET(LED_OCCUPIED_FRONT_OUTER)
    ENDIF
  ENDIF
DONE

ONSENSOR(-SENSOR_OCCUPIED_FRONT_INNER_1)
  IF(-SENSOR_OCCUPIED_FRONT_INNER_1)
    SET(LED_OCCUPIED_FRONT_INNER)
  ELSE 
    IFNOT(-SENSOR_OCCUPIED_FRONT_INNER_2)
      RESET(LED_OCCUPIED_FRONT_INNER)
    ENDIF
  ENDIF
DONE

ONSENSOR(-SENSOR_OCCUPIED_FRONT_INNER_2)
  IF(-SENSOR_OCCUPIED_FRONT_INNER_2)
    SET(LED_OCCUPIED_FRONT_INNER)
  ELSE 
    IFNOT(-SENSOR_OCCUPIED_FRONT_INNER_1)
      RESET(LED_OCCUPIED_FRONT_INNER)
    ENDIF
  ENDIF
DONE

ONSENSOR(-SENSOR_OCCUPIED_LOOP_1)
  IF(-SENSOR_OCCUPIED_LOOP_1)
    PRINT("LOOP 1 ON")
    SET(LED_OCCUPIED_LOOP)
  ELSE 
    IFNOT(-SENSOR_OCCUPIED_LOOP_2)
      PRINT("LOOP 1 OFF")
      RESET(LED_OCCUPIED_LOOP)
    ENDIF
  ENDIF
DONE

ONSENSOR(-SENSOR_OCCUPIED_LOOP_2)
  IF(-SENSOR_OCCUPIED_LOOP_2)
    PRINT("LOOP 2 ON")

    SET(LED_OCCUPIED_LOOP)
  ELSE 
    IFNOT(-SENSOR_OCCUPIED_LOOP_1)
        PRINT("LOOP 2 OFF")
      RESET(LED_OCCUPIED_LOOP)
    ENDIF
  ENDIF
DONE

ONSENSOR(-SENSOR_OCCUPIED_REAR_OUTER_1)
  IF(-SENSOR_OCCUPIED_REAR_OUTER_1)
    SET(LED_OCCUPIED_REAR_OUTER)
  ELSE 
    IFNOT(-SENSOR_OCCUPIED_REAR_OUTER_2)
      RESET(LED_OCCUPIED_REAR_OUTER)
    ENDIF
  ENDIF
DONE

ONSENSOR(-SENSOR_OCCUPIED_REAR_OUTER_2)
  IF(-SENSOR_OCCUPIED_REAR_OUTER_2)
    SET(LED_OCCUPIED_REAR_OUTER)
  ELSE 
    IFNOT(-SENSOR_OCCUPIED_REAR_OUTER_1)
      RESET(LED_OCCUPIED_REAR_OUTER)
    ENDIF
  ENDIF
DONE

ONSENSOR(-SENSOR_OCCUPIED_REAR_INNER_1)
  IF(-SENSOR_OCCUPIED_REAR_INNER_1)
    SET(LED_OCCUPIED_REAR_INNER)
  ELSE 
    IFNOT(-SENSOR_OCCUPIED_REAR_INNER_2)
      RESET(LED_OCCUPIED_REAR_INNER)
    ENDIF
  ENDIF
DONE

ONSENSOR(-SENSOR_OCCUPIED_REAR_INNER_2)
  IF(-SENSOR_OCCUPIED_REAR_INNER_2)
    SET(LED_OCCUPIED_REAR_INNER)
  ELSE 
    IFNOT(-SENSOR_OCCUPIED_REAR_INNER_1)
      RESET(LED_OCCUPIED_REAR_INNER)
    ENDIF
  ENDIF
DONE

ONSENSOR(-SENSOR_OCCUPIED_YARD)
  IF(-SENSOR_OCCUPIED_YARD)
    SET(LED_OCCUPIED_YARD)
  ELSE
    RESET(LED_OCCUPIED_YARD)
  ENDIF
DONE

ONSENSOR(-SENSOR_LEFT_OUTER_CURVE)
  IF(-SENSOR_LEFT_OUTER_CURVE)
    SET(LED_OCCUPIED_LEFT_CURVE_OUTER)
  ELSE
    RESET(LED_OCCUPIED_LEFT_CURVE_OUTER)
  ENDIF
DONE

ONSENSOR(-SENSOR_LEFT_INNER_CURVE)
  IF(-SENSOR_LEFT_INNER_CURVE)
    SET(LED_OCCUPIED_LEFT_CURVE_INNER)
  ELSE
    RESET(LED_OCCUPIED_LEFT_CURVE_INNER)
  ENDIF
DONE

SEQUENCE(SEQUENCE_STARTUP)
  SET(LED_FRONT_RIGHT_CROSSOVER_INNER)
  SET(LED_FRONT_RIGHT_CROSSOVER_OUTER)
  SET(LED_FRONT_RIGHT_LOOP_INNER)
  SET(LED_ENGINE_YARD)
  SET(LED_RIGHT_LOOP)
  SET(LED_GOODS)
  SET(LED_GOODS_OR_GOODS_SHED_GOODS)
  SET(LED_GOODS_FRONT)
  SET(LED_PASSENGER_FRONT)

  SET(LED_REAR_REVERSE_LOOP_CLOSED)
  SET(LED_BACK_LEFT_CROSSOVER_OUTER)
  SET(LED_BACK_LEFT_CROSSOVER_INNER)
  SET(LED_FRONT_LEFT_CROSSOVER_OUTER)
  SET(LED_FRONT_LEFT_CROSSOVER_INNER)
  POWERON
DONE



