// #include "EXRAILMacros.h"

#ifdef ARDUINO_ARCH_ESP32
HAL_IGNORE_DEFAULTS

// Control Board
HAL(PCF8575, 320, 16, {I2CMux_1,SubBus_0,0x23})
HAL(PCF8575, 300, 16, {I2CMux_1,SubBus_1,0x20})
HAL(PCA9685, 380, 16, {I2CMux_1,SubBus_2,0x45})
HAL(PCA9685, 360, 16, {I2CMux_1,SubBus_3,0x44})
HAL(PCA9685, 400, 16, {I2CMux_1,SubBus_4,0x46})
HAL(PCA9685, 340, 16, {I2CMux_1,SubBus_5,0x43})
HAL(HALDisplay<OLED>, 0, {I2CMux_1, SubBus_6, 0x3d}, 128, 64)
HAL(PCF8575, 420, 16, {I2CMux_1,SubBus_7,0x20})

// Right Side Layout
HAL(PCF8575, 220, 16, {I2CMux_2,SubBus_0,0x22})
HAL(PCA9685, 100, 16, {I2CMux_2,SubBus_1,0x40})

// Left Side Layout
HAL(PCF8575, 200, 16, {I2CMux_3,SubBus_3,0x21})
HAL(PCA9685, 120, 16, {I2CMux_3,SubBus_5,0x41})
HAL(PCA9685, 140, 16, {I2CMux_3,SubBus_4,0x42})
HAL(EXTurntable, 600, 1, {I2CMux_3,SubBus_2,0x60})
#endif 

#define FUNCTIONS_TYPE_1 "/F1 Sound ON-OFF/*F2 Whistle 1/*F3 Whistle 2/*F4 Brake/F5 Cylinder Cock/*F6 Wheel Slip/F7 Coal Shoveling/F8 Injector Valve/F9 Safety Valve/*F10 Guards Whistle/*F11 Coupling/*F12 Carrage Brake Squeal/F13 Flange Squeal/F14 Blower/*F15 Door Closed/F16 Firemans Breakfast/F17 Blowdown/*F18 Bell/F19 Water Fill/F20 Chuffing Coasting/////F25 Shunting Mode/*F26 Creep Mode/*F27 Apply Brake/F28 Auto Function Control"
#define FUNCTIONS_SMALL_LOCO "/////F5 Shunting/*F6 Creep/*F7 Brake"

#define ON_TURNTABLE_BUTTON(button, turntable_id, position, reverse_position, led) \
  ONBUTTON(button) \
    CALL(TURNTABLE_LEDS_OFF) \
    IFTTPOSITION(turntable_id, position) \
      ROTATE(turntable_id, reverse_position, Turn) \
      BLINK(led,1000,500) \
    ELSE \
      ROTATE(turntable_id, position, Turn) \
      BLINK(led,500,500) \
    ENDIF \
    WAITFORTT(turntable_id) \
    SET(led) \
    RETURN \
  DONE

#define ON_SENSOR_LED(sensor, led) \
  ONSENSOR(sensor) \
    IF(sensor) \
      SET(led) \
    ELSE \
      RESET(led) \
    ENDIF \
  DONE

#define ON_SENSOR_PAIR_LED(sensor, other_sensor, led) \
  ONSENSOR(sensor) \
    IF(sensor) \
      SET(led) \
    ELSE \
      IFNOT(other_sensor) \
        RESET(led) \
      ENDIF \
    ENDIF \
  DONE

#define ON_BUTTON_TOGGLE_TURNOUT(button, turnout) \
  ONBUTTON(button) \
    TOGGLE_TURNOUT(turnout) \
  DONE

#define ON_UNCOUPLER_LED(uncoupler, led) \
  ONTHROW(uncoupler) \
    SET(led) \
  DONE \
  ONCLOSE(uncoupler) \
    RESET(led) \
  DONE

#define ON_CROSSOVER_TURNOUT(crossover, outer_turnout, inner_turnout) \
  ONTHROW(crossover) \
    THROW(outer_turnout) \
    THROW(inner_turnout) \
  DONE \
  ONCLOSE(crossover) \
    CLOSE(outer_turnout) \
    CLOSE(inner_turnout) \
  DONE

#define ON_TURNOUT_PAIR_LED(turnout, thrown_led, closed_led) \
  ONTHROW(turnout) \
    SET(thrown_led) \
    RESET(closed_led) \
  DONE \
  ONCLOSE(turnout) \
    SET(closed_led) \
    RESET(thrown_led) \
  DONE

#define ON_CROSSOVER_LED(crossover, outer_led, crossed_led, inner_led) \
  ONTHROW(crossover) \
    RESET(outer_led) \
    SET(crossed_led) \
    RESET(inner_led) \
  DONE \
  ONCLOSE(crossover) \
    SET(outer_led) \
    RESET(crossed_led) \
    SET(inner_led) \
  DONE


// HM7000_826E, b90f634c
ROSTER(5,"A4 William Whitehall", FUNCTIONS_TYPE_1)

// HM7000_0B45, fd7c1c3b
ROSTER(6,"Green DB Schenker Class 08", FUNCTIONS_SMALL_LOCO)
#ifdef ARDUINO_ARCH_ESP32

// HM7000_FBEB, 787ff47f
ROSTER(7,"Duchess of Montrose", FUNCTIONS_TYPE_1)

// HM7000_08AE, e4a048bc
ROSTER(8,"Red DB Schenker Class 08", FUNCTIONS_SMALL_LOCO)

// HM7000_0B56, ad3c5681
ROSTER(9,"Terrier", FUNCTIONS_SMALL_LOCO)

#endif

// HM7000_929D, db00c17c
ROSTER(10,"Class 37",
  "F0 Day Light/F1 Engine Start/*F2 Horns 1/*F3 Horns 2/*F4 Brake Squeal/*F5 Diesel Notch Up/*F6 Diesel Notch Down/*F7 Idle/F8 Engine Thrash/F9 Diesel Cold Start/F10 Compressor/F11 Spirax Valve/F12 Cooling Fan/*F13 AWS Indicator/F14 Flange Squeal/*F15 Brake Release/*F16 Door Closed/*F17 AWS Indicator/F18 Diesel Primer/*F19 Guards Whistle/*F20 Wagons Clanking/F21 Day Light/F22 Rear Light/F23 Cabin Light/F24 Aux Lighting/F26 Shunting Mode/*F27 Creep Mode/*F28 Apply Brake/F29 Automated Function Control"
)

// HM7000_0AE3, 86530533
// assigned to 11, no loco

// HM7000_11CF, b01d3b43
ROSTER(12,"LNER J50", FUNCTIONS_SMALL_LOCO)

#ifdef ARDUINO_ARCH_ESP32

ALIAS(SEQUENCE_STARTUP)
ALIAS(TURNTABLE_LEDS_OFF)

// This is the startup sequence, 
AUTOSTART
  START(SEQUENCE_STARTUP)    
DONE 
#endif 

// point alias pins
ALIAS(POINT_FRONT_RIGHT_CROSS_OUTER_PIN    , 100)
ALIAS(POINT_FRONT_RIGHT_REVERSE_LOOP_PIN   , 101)
ALIAS(POINT_FRONT_RIGHT_LOOP_PIN           , 102)
ALIAS(POINT_ENGINE_SHED_PIN                , 103)
ALIAS(POINT_YARD_PIN                       , 104)
ALIAS(POINT_FRONT_RIGHT_CROSS_INNER_PIN    , 105)
ALIAS(POINT_ENGINE_SHED_TO_TURNTABLE_PIN   , 106)
ALIAS(POINT_FRONT_LEFT_CROSS_OUTER_PIN     , 120)
ALIAS(POINT_FRONT_LEFT_LOOP_PIN            , 121)
ALIAS(POINT_BACK_LEFT_CROSS_OUTER_PIN      , 122)
ALIAS(POINT_BACK_LEFT_REVERSE_LOOP_PIN     , 123)
ALIAS(POINT_GOODS_OR_PASSENGER_PIN         , 124)
ALIAS(POINT_PASSENGER_SIDINGS_PIN          , 125)
ALIAS(POINT_GOODS_SHED_PIN                 , 126)
ALIAS(POINT_GOODS_SIDINGS_PIN              , 127)
ALIAS(POINT_FRONT_LEFT_CROSS_INNER_PIN     , 128)
ALIAS(POINT_BACK_LEFT_CROSS_INNER_PIN      , 129)
ALIAS(POINT_BACK_RIGHT_CROSS_OUTER_PIN     , 130)
ALIAS(POINT_BACK_RIGHT_CROSS_INNER_PIN     , 131)


// point alias
ALIAS(POINT_FRONT_RIGHT_CROSS_OUTER    , 100)
ALIAS(POINT_FRONT_RIGHT_REVERSE_LOOP   , 101)
ALIAS(POINT_FRONT_RIGHT_LOOP           , 102)
ALIAS(POINT_ENGINE_SHED                , 103)
ALIAS(POINT_YARD                       , 104)
ALIAS(POINT_FRONT_RIGHT_CROSS_INNER    , 105)
ALIAS(POINT_ENGINE_SHED_TO_TURNTABLE   , 106)
ALIAS(POINT_FRONT_LEFT_CROSS_OUTER     , 120)
ALIAS(POINT_FRONT_LEFT_LOOP            , 121)
ALIAS(POINT_BACK_LEFT_CROSS_OUTER      , 122)
ALIAS(POINT_BACK_LEFT_REVERSE_LOOP     , 123)
ALIAS(POINT_GOODS_OR_PASSENGER         , 124)
ALIAS(POINT_PASSENGER_SIDINGS          , 125)
ALIAS(POINT_GOODS_SHED                 , 126)
ALIAS(POINT_GOODS_SIDINGS              , 127)
ALIAS(POINT_FRONT_LEFT_CROSS_INNER     , 128)
ALIAS(POINT_BACK_LEFT_CROSS_INNER      , 129)
ALIAS(POINT_BACK_RIGHT_CROSS_OUTER     , 130)
ALIAS(POINT_BACK_RIGHT_CROSS_INNER     , 131)


ALIAS(POINT_FRONT_RIGHT_CROSSOVER, 1001)
ALIAS(POINT_FRONT_LEFT_CROSSOVER , 1002)
ALIAS(POINT_BACK_LEFT_CROSSOVER  , 1003)
ALIAS(POINT_BACK_RIGHT_CROSSOVER , 1004)

#ifdef ARDUINO_ARCH_ESP32

// uncoupler alias pins
ALIAS(UNCOUPLER_FRONT_RIGHT_OUTER_PIN, 108)
ALIAS(UNCOUPLER_FRONT_RIGHT_INNER_PIN, 109)
ALIAS(UNCOUPLER_FRONT_RIGHT_LOOP_PIN , 140)
ALIAS(UNCOUPLER_FRONT_LEFT_OUTER_PIN , 141)
ALIAS(UNCOUPLER_FRONT_LEFT_INNER_PIN , 142)
ALIAS(UNCOUPLER_FRONT_LEFT_LOOP_PIN  , 143)
ALIAS(UNCOUPLER_PASSENGER_REAR_PIN   , 144)
ALIAS(UNCOUPLER_PASSENGER_FRONT_PIN  , 145)
ALIAS(UNCOUPLER_GOODS_SHED_PIN       , 146)
ALIAS(UNCOUPLER_GOODS_BACK_PIN       , 147)
ALIAS(UNCOUPLER_GOODS_FRONT_PIN      , 148)

// uncoupler alias
ALIAS(UNCOUPLER_FRONT_RIGHT_OUTER, 108)
ALIAS(UNCOUPLER_FRONT_RIGHT_INNER, 109)
ALIAS(UNCOUPLER_FRONT_RIGHT_LOOP , 140)
ALIAS(UNCOUPLER_FRONT_LEFT_OUTER , 141)
ALIAS(UNCOUPLER_FRONT_LEFT_INNER , 142)
ALIAS(UNCOUPLER_FRONT_LEFT_LOOP  , 143)
ALIAS(UNCOUPLER_PASSENGER_REAR   , 144)
ALIAS(UNCOUPLER_PASSENGER_FRONT  , 145)
ALIAS(UNCOUPLER_GOODS_SHED       , 146)
ALIAS(UNCOUPLER_GOODS_BACK       , 147)
ALIAS(UNCOUPLER_GOODS_FRONT      , 148)

//button alias
ALIAS(BUTTON_KILL                                , 300)
ALIAS(BUTTON_POINT_BACK_LEFT_CROSSOVER           , 301)
ALIAS(BUTTON_POINT_BACK_LEFT_REVERSE_LOOP        , 302)
ALIAS(BUTTON_UNCOUPLE_BACK_SIDING                , 303)
ALIAS(BUTTON_UNCOUPLE_GOODS_SHED                 , 304)
ALIAS(BUTTON_BACK_LEFT_GOODS_SIDINGS             , 305)
ALIAS(BUTTON_UNCOUPLE_FRONT_SIDING               , 306)
ALIAS(BUTTON_POINT_FRONT_LEFT_LOOP               , 307)
ALIAS(BUTTON_POINT_FRONT_LEFT_CROSSOVER          , 308)
ALIAS(BUTTON_UNCOUPLE_OUTER_LEFT                 , 309)
ALIAS(BUTTON_UNCOUPLE_INNER_LEFT                 , 310)
ALIAS(BUTTON_UNCOUPLE_LEFT_LOOP                  , 311)
ALIAS(BUTTON_POINT_GOODS_SHED                    , 312)
ALIAS(BUTTON_UNCOUPLE_FRONT_PASSENGER            , 313)
ALIAS(BUTTON_UNCOUPLE_REAR_PASSENGER             , 314)
ALIAS(BUTTON_POINT_PASSENGER_SIDINGS             , 315)


ALIAS(BUTTON_POINT_GOODS_OR_PASSENGER            , 320)
ALIAS(BUTTON_POINT_YARD                          , 321)
ALIAS(BUTTON_UNCOUPLE_RIGHT_LOOP                 , 322)
ALIAS(BUTTON_UNCOUPLE_INNER_RIGHT                , 323)
ALIAS(BUTTON_POINT_ENGINE_SHED                   , 324)
ALIAS(BUTTON_POINT_FRONT_RIGHT_LOOP              , 325)
ALIAS(BUTTON_UNCOUPLE_OUTER_RIGHT                , 326)
ALIAS(BUTTON_POINT_FRONT_RIGHT_CROSSOVER         , 327)
ALIAS(BUTTON_POINT_FRONT_RIGHT_REVERSE_LOOP      , 328)
ALIAS(BUTTON_POINT_BACK_RIGHT_CROSSOVER          , 329)
ALIAS(BUTTON_POINT_TO_TURNTABLE                  , 330)

ALIAS(BUTTON_TURNTABLE_ENTRY                     , 420)
ALIAS(BUTTON_TURNTABLE_2                         , 421)
ALIAS(BUTTON_TURNTABLE_3                         , 422)
ALIAS(BUTTON_TURNTABLE_4                         , 423)
ALIAS(BUTTON_TURNTABLE_5                         , 424)
ALIAS(BUTTON_TURNTABLE_6                         , 425)

// sensor pins
ALIAS(SENSOR_OCCUPIED_RIGHT_OUTER_CURVE , 223)
ALIAS(SENSOR_OCCUPIED_RIGHT_INNER_CURVE , 222)
ALIAS(SENSOR_OCCUPIED_REVERSE_LOOP      , 201)
ALIAS(SENSOR_OCCUPIED_FRONT_OUTER_LEFT  , 209)
ALIAS(SENSOR_OCCUPIED_FRONT_OUTER_RIGHT , 227)
ALIAS(SENSOR_OCCUPIED_FRONT_INNER_LEFT  , 206)
ALIAS(SENSOR_OCCUPIED_FRONT_INNER_RIGHT , 226)
ALIAS(SENSOR_OCCUPIED_LOOP_1            , 205)
ALIAS(SENSOR_OCCUPIED_LOOP_2            , 225)
ALIAS(SENSOR_OCCUPIED_REAR_OUTER_LEFT   , 204)
ALIAS(SENSOR_OCCUPIED_REAR_OUTER_RIGHT  , 221)
ALIAS(SENSOR_OCCUPIED_REAR_INNER_LEFT   , 203)
ALIAS(SENSOR_OCCUPIED_REAR_INNER_RIGHT  , 220)
ALIAS(SENSOR_OCCUPIED_YARD              , 202)
ALIAS(SENSOR_OCCUPIED_LEFT_INNER_CURVE  , 207)
ALIAS(SENSOR_OCCUPIED_LEFT_OUTER_CURVE  , 208)
ALIAS(SENSOR_OCCUPIED_TO_TURNTABLE_LEFT , 200)
ALIAS(SENSOR_OCCUPIED_TO_TURNTABLE_RIGHT, 224)

JMRI_SENSOR(200,16)
JMRI_SENSOR(220,16)
JMRI_SENSOR(300,16)
JMRI_SENSOR(320,16)
JMRI_SENSOR(420,16)
#endif



// points
// "Front Right Crossover Outer"
SERVO_TURNOUT(POINT_FRONT_RIGHT_CROSS_OUTER , POINT_FRONT_RIGHT_CROSS_OUTER_PIN , 290, 320, Instant, HIDDEN)
// "Front Right Crossover Inner"
SERVO_TURNOUT(POINT_FRONT_RIGHT_CROSS_INNER , POINT_FRONT_RIGHT_CROSS_INNER_PIN , 265, 290, Instant, HIDDEN)
SERVO_TURNOUT(POINT_FRONT_RIGHT_REVERSE_LOOP, POINT_FRONT_RIGHT_REVERSE_LOOP_PIN, 260, 300, Instant, "Reverse Loop Front Right")
SERVO_TURNOUT(POINT_FRONT_RIGHT_LOOP        , POINT_FRONT_RIGHT_LOOP_PIN        , 280, 320, Instant, "Loop Front Right")
SERVO_TURNOUT(POINT_ENGINE_SHED             , POINT_ENGINE_SHED_PIN             , 340, 290, Instant, "To Engine Shed")
SERVO_TURNOUT(POINT_YARD                    , POINT_YARD_PIN                    , 350, 310, Instant, "To Yard")
SERVO_TURNOUT(POINT_ENGINE_SHED_TO_TURNTABLE, POINT_ENGINE_SHED_TO_TURNTABLE_PIN, 350, 310, Instant, "To Turntable")

#ifdef ARDUINO_ARCH_ESP32

// "Front Left Crossover Outer"
SERVO_TURNOUT(POINT_FRONT_LEFT_CROSS_OUTER  , POINT_FRONT_LEFT_CROSS_OUTER_PIN  , 370, 310, Instant, HIDDEN)
// "Front Left Crossover Inner"
SERVO_TURNOUT(POINT_FRONT_LEFT_CROSS_INNER  , POINT_FRONT_LEFT_CROSS_INNER_PIN  , 255, 290, Instant, HIDDEN)
SERVO_TURNOUT(POINT_FRONT_LEFT_LOOP         , POINT_FRONT_LEFT_LOOP_PIN         , 360, 310, Instant, "Loop Front Left") // 121

// "Back Left Crossover Outer"
SERVO_TURNOUT(POINT_BACK_LEFT_CROSS_OUTER   , POINT_BACK_LEFT_CROSS_OUTER_PIN   , 320, 360, Instant, HIDDEN)
// "Back Left Crossover Inner"
SERVO_TURNOUT(POINT_BACK_LEFT_CROSS_INNER   , POINT_BACK_LEFT_CROSS_INNER_PIN   , 245, 280, Instant, HIDDEN)
SERVO_TURNOUT(POINT_BACK_LEFT_REVERSE_LOOP  , POINT_BACK_LEFT_REVERSE_LOOP_PIN  , 260, 295, Instant, "Reverse Loop Back Left")

SERVO_TURNOUT(POINT_GOODS_OR_PASSENGER      , POINT_GOODS_OR_PASSENGER_PIN      , 300, 350, Instant, "Goods or Passenger")
SERVO_TURNOUT(POINT_PASSENGER_SIDINGS       , POINT_PASSENGER_SIDINGS_PIN       , 280, 320, Instant, "Passenger Sidings")

SERVO_TURNOUT(POINT_GOODS_SHED              , POINT_GOODS_SHED_PIN              , 250, 295, Instant, "Goods Shed") // 126
SERVO_TURNOUT(POINT_GOODS_SIDINGS           , POINT_GOODS_SIDINGS_PIN           , 278, 310, Instant, "Goods Sidings")


SERVO_TURNOUT(POINT_BACK_RIGHT_CROSS_OUTER  , POINT_BACK_RIGHT_CROSS_OUTER_PIN  , 350, 315, Instant, HIDDEN)
SERVO_TURNOUT(POINT_BACK_RIGHT_CROSS_INNER  , POINT_BACK_RIGHT_CROSS_INNER_PIN  , 340, 305, Instant, HIDDEN)

VIRTUAL_TURNOUT(POINT_FRONT_RIGHT_CROSSOVER, "Crossover Front Right")
VIRTUAL_TURNOUT(POINT_FRONT_LEFT_CROSSOVER , "Crossover Front Left")
VIRTUAL_TURNOUT(POINT_BACK_LEFT_CROSSOVER  , "Crossover Back Left")
VIRTUAL_TURNOUT(POINT_BACK_RIGHT_CROSSOVER , "Crossover Back Right")


// UNCOUPLERS, are defined as servo_turnouts
SERVO_TURNOUT(UNCOUPLER_FRONT_RIGHT_OUTER, UNCOUPLER_FRONT_RIGHT_OUTER_PIN, 330, 250, Instant, "Uncoupler Front Right Outer")      // 108
SERVO_TURNOUT(UNCOUPLER_FRONT_RIGHT_INNER, UNCOUPLER_FRONT_RIGHT_INNER_PIN, 330, 250, Instant, "Uncoupler Front Right Inner")      // 109
SERVO_TURNOUT(UNCOUPLER_FRONT_RIGHT_LOOP , UNCOUPLER_FRONT_RIGHT_LOOP_PIN , 330, 250, Instant, "Uncoupler Front Right Loop")       // 140
SERVO_TURNOUT(UNCOUPLER_FRONT_LEFT_OUTER , UNCOUPLER_FRONT_LEFT_OUTER_PIN , 380, 310, Instant, "Uncoupler Front Left Outer")       // 141
SERVO_TURNOUT(UNCOUPLER_FRONT_LEFT_INNER , UNCOUPLER_FRONT_LEFT_INNER_PIN , 340, 250, Instant, "Uncoupler Front Left Inner")       // 142
SERVO_TURNOUT(UNCOUPLER_FRONT_LEFT_LOOP  , UNCOUPLER_FRONT_LEFT_LOOP_PIN  , 330, 250, Instant, "Uncoupler Front Left Loop")        // 143
SERVO_TURNOUT(UNCOUPLER_PASSENGER_REAR   , UNCOUPLER_PASSENGER_REAR_PIN   , 300, 250, Instant, "Uncoupler Passenger Rear Siding")  // 144
SERVO_TURNOUT(UNCOUPLER_PASSENGER_FRONT  , UNCOUPLER_PASSENGER_FRONT_PIN  , 300, 250, Instant, "Uncoupler Passenger Front Siding") // 145
SERVO_TURNOUT(UNCOUPLER_GOODS_SHED       , UNCOUPLER_GOODS_SHED_PIN       , 280, 350, Instant, "Uncoupler Goods Shed Siding")      // 146
SERVO_TURNOUT(UNCOUPLER_GOODS_BACK       , UNCOUPLER_GOODS_BACK_PIN       , 330, 380, Instant, "Uncoupler Rear Goods Siding")      // 147
SERVO_TURNOUT(UNCOUPLER_GOODS_FRONT      , UNCOUPLER_GOODS_FRONT_PIN      , 330, 380, Instant, "Uncoupler Front Goods Siding")     // 148


ALIAS(LED_FRONT_RIGHT_CROSSOVER_CROSSED, 340)
ALIAS(LED_FRONT_RIGHT_CROSSOVER_INNER  , 341)
ALIAS(LED_FRONT_RIGHT_CROSSOVER_OUTER  , 342)
ALIAS(LED_FRONT_RIGHT_REVERSE_LOOP     , 343)
ALIAS(LED_FRONT_RIGHT_LOOP             , 344)
ALIAS(LED_FRONT_RIGHT_LOOP_INNER       , 345)
ALIAS(LED_ENGINE                       , 346)
ALIAS(LED_ENGINE_YARD                  , 347)
ALIAS(LED_YARD                         , 405)
ALIAS(LED_RIGHT_LOOP                   , 404)
ALIAS(LED_TO_TURNTABLE                 , 407)
ALIAS(LED_ENGINE_SHED_SIDING           , 406)

ALIAS(LED_OCCUPIED_RIGHT_CURVE_OUTER   , 350)
ALIAS(LED_OCCUPIED_RIGHT_CURVE_INNER   , 351)
ALIAS(LED_OCCUPIED_REVERSE_LOOP        , 352)

ALIAS(LED_UNCOUPLE_FRONT_RIGHT_OUTER   , 353)
ALIAS(LED_UNCOUPLE_FRONT_RIGHT_INNER   , 354)
ALIAS(LED_UNCOUPLE_FRONT_RIGHT_LOOP    , 355)

ALIAS(LED_PASSENGER                    , 360)
ALIAS(LED_GOODS                        , 361)
ALIAS(LED_PASSENGER_FRONT              , 362)
ALIAS(LED_PASSENGER_BACK               , 363)
ALIAS(LED_REAR_REVERSE_LOOP_CLOSED     , 364)
ALIAS(LED_REAR_REVERSE_LOOP_THROWN     , 365)
ALIAS(LED_UNCOUPLE_PASSENGER_FRONT     , 366)
ALIAS(LED_UNCOUPLE_PASSENGER_BACK      , 367)

ALIAS(LED_BACK_RIGHT_CROSSOVER_CROSSED, 368)
ALIAS(LED_BACK_RIGHT_CROSSOVER_INNER  , 369)
ALIAS(LED_BACK_RIGHT_CROSSOVER_OUTER  , 370)

ALIAS(LED_OCCUPIED_FRONT_OUTER         , 371)
ALIAS(LED_OCCUPIED_FRONT_INNER         , 372)
ALIAS(LED_OCCUPIED_LOOP                , 373)
ALIAS(LED_OCCUPIED_REAR_INNER_LEFT     , 374)
ALIAS(LED_OCCUPIED_REAR_OUTER_LEFT     , 375)

ALIAS(LED_OCCUPIED_REAR_INNER_RIGHT    , 349)
ALIAS(LED_OCCUPIED_REAR_OUTER_RIGHT    , 348)


ALIAS(LED_BACK_LEFT_CROSSOVER_OUTER    , 380)
ALIAS(LED_BACK_LEFT_CROSSOVER_CROSSED  , 381)
ALIAS(LED_BACK_LEFT_CROSSOVER_INNER    , 382)
ALIAS(LED_FRONT_LEFT_CROSSOVER_OUTER   , 383)
ALIAS(LED_FRONT_LEFT_CROSSOVER_CROSSED , 384)
ALIAS(LED_FRONT_LEFT_CROSSOVER_INNER   , 385)
ALIAS(LED_FRONT_LEFT_LOOP              , 386)
ALIAS(LED_GOODS_OR_GOODS_SHED_GOODS    , 387)
ALIAS(LED_GOODS_OR_GOODS_SHED_SHED     , 388)
ALIAS(LED_GOODS_FRONT                  , 389)
ALIAS(LED_GOODS_BACK                   , 390)


ALIAS(LED_UNCOUPLE_FRONT_LEFT_LOOP     , 400)
ALIAS(LED_UNCOUPLE_GOODS_SHED          , 392)
ALIAS(LED_UNCOUPLE_GOODS_FRONT         , 393)
ALIAS(LED_UNCOUPLE_GOODS_BACK          , 394)

ALIAS(LED_OCCUPIED_LEFT_CURVE_INNER    , 395)

ALIAS(LED_OCCUPIED_LEFT_CURVE_OUTER    , 391)
ALIAS(LED_UNCOUPLE_FRONT_LEFT_OUTER    , 401)
ALIAS(LED_UNCOUPLE_FRONT_LEFT_INNER    , 402)
ALIAS(LED_OCCUPIED_YARD                , 403)


// LEDs on mimic
CONFIGURE_SERVO(LED_FRONT_RIGHT_CROSSOVER_CROSSED, 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_RIGHT_CROSSOVER_INNER  , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_RIGHT_CROSSOVER_OUTER  , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_RIGHT_REVERSE_LOOP     , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_RIGHT_LOOP             , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_RIGHT_LOOP_INNER       , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_ENGINE                       , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_ENGINE_YARD                  , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_YARD                         , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_RIGHT_LOOP                   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_PASSENGER                    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_GOODS                        , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_PASSENGER_FRONT              , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_PASSENGER_BACK               , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_REAR_REVERSE_LOOP_CLOSED     , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_REAR_REVERSE_LOOP_THROWN     , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_TO_TURNTABLE                 , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_ENGINE_SHED_SIDING           , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)


CONFIGURE_SERVO(LED_OCCUPIED_RIGHT_CURVE_OUTER   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_RIGHT_CURVE_INNER   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_REVERSE_LOOP        , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_FRONT_OUTER         , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_FRONT_INNER         , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_LOOP                , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_REAR_OUTER_LEFT     , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_REAR_INNER_LEFT     , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_REAR_OUTER_RIGHT    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_REAR_INNER_RIGHT    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_YARD                , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)


CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_RIGHT_OUTER   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_RIGHT_INNER   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_RIGHT_LOOP    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)

CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_LEFT_OUTER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_LEFT_INNER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_LEFT_LOOP     , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)

CONFIGURE_SERVO(LED_BACK_LEFT_CROSSOVER_OUTER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_BACK_LEFT_CROSSOVER_CROSSED  , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_BACK_LEFT_CROSSOVER_INNER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_LEFT_CROSSOVER_OUTER   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_LEFT_CROSSOVER_CROSSED , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_LEFT_CROSSOVER_INNER   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_FRONT_LEFT_LOOP              , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_GOODS_OR_GOODS_SHED_SHED     , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_GOODS_OR_GOODS_SHED_GOODS    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_GOODS_FRONT                  , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_GOODS_BACK                   , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)

CONFIGURE_SERVO(LED_UNCOUPLE_FRONT_LEFT_INNER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_GOODS_SHED          , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_GOODS_FRONT         , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_UNCOUPLE_GOODS_BACK          , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)

CONFIGURE_SERVO(LED_OCCUPIED_LEFT_CURVE_INNER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_OCCUPIED_LEFT_CURVE_OUTER    , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)

CONFIGURE_SERVO(LED_BACK_RIGHT_CROSSOVER_CROSSED, 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_BACK_RIGHT_CROSSOVER_INNER  , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_BACK_RIGHT_CROSSOVER_OUTER  , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)

#endif 

ALIAS(TURNTABLE_STALL_ENTRY, 594)
ALIAS(TURNTABLE_STALL_3, 2240)
ALIAS(TURNTABLE_STALL_4, 2357)
ALIAS(TURNTABLE_STALL_5, 2462)
ALIAS(TURNTABLE_STALL_6, 2590)

ALIAS(TURNTABLE_STALL_REVERSE_ENTRY, 2194)
ALIAS(TURNTABLE_STALL_REVERSE_3, 640)
ALIAS(TURNTABLE_STALL_REVERSE_4, 757)
ALIAS(TURNTABLE_STALL_REVERSE_5, 862)
ALIAS(TURNTABLE_STALL_REVERSE_6, 990)

ALIAS(TURNTABLE_POSITION_ENTRY , 1)
ALIAS(TURNTABLE_POSITION_2     , 2)
ALIAS(TURNTABLE_POSITION_3     , 3)
ALIAS(TURNTABLE_POSITION_4     , 4)
ALIAS(TURNTABLE_POSITION_5     , 5)
ALIAS(TURNTABLE_POSITION_6     , 6)
ALIAS(TURNTABLE_POSITION_REVERSE_ENTRY , 10)
ALIAS(TURNTABLE_POSITION_REVERSE_2 , 12)
ALIAS(TURNTABLE_POSITION_REVERSE_3 , 13)
ALIAS(TURNTABLE_POSITION_REVERSE_4 , 14)
ALIAS(TURNTABLE_POSITION_REVERSE_5 , 15)
ALIAS(TURNTABLE_POSITION_REVERSE_6 , 16)


ALIAS(TURNTABLE_ID_1, 1)
// full rotation = 3200
EXTT_TURNTABLE(TURNTABLE_ID_1,600,0,"EX-Turntable 1")
TT_ADDPOSITION(TURNTABLE_ID_1, TURNTABLE_POSITION_ENTRY,TURNTABLE_STALL_ENTRY,0,"Entry")
TT_ADDPOSITION(TURNTABLE_ID_1, TURNTABLE_POSITION_REVERSE_ENTRY,TURNTABLE_STALL_REVERSE_ENTRY,0,"Reverse Entry")
// TT_ADDPOSITION(1,2,800,0, "Stall 2")
// TT_ADDPOSITION(1,3,1200,0,"Stall 3")
TT_ADDPOSITION(TURNTABLE_ID_1, TURNTABLE_POSITION_3,TURNTABLE_STALL_3,0,"Stall 3")
TT_ADDPOSITION(TURNTABLE_ID_1, TURNTABLE_POSITION_REVERSE_3,TURNTABLE_STALL_REVERSE_3,0,"Reverse 3")
TT_ADDPOSITION(TURNTABLE_ID_1, TURNTABLE_POSITION_4,TURNTABLE_STALL_4,0,"Stall 4")
TT_ADDPOSITION(TURNTABLE_ID_1, TURNTABLE_POSITION_REVERSE_4,TURNTABLE_STALL_REVERSE_4,0,"Reverse 4")
TT_ADDPOSITION(TURNTABLE_ID_1, TURNTABLE_POSITION_5,TURNTABLE_STALL_5,0,"Stall 5")
TT_ADDPOSITION(TURNTABLE_ID_1, TURNTABLE_POSITION_REVERSE_5,TURNTABLE_STALL_REVERSE_5,0,"Reverse 5")
TT_ADDPOSITION(TURNTABLE_ID_1, TURNTABLE_POSITION_6,TURNTABLE_STALL_6,0,"Stall 6")
TT_ADDPOSITION(TURNTABLE_ID_1, TURNTABLE_POSITION_REVERSE_6,TURNTABLE_STALL_REVERSE_6,0,"Reverse 6")
// TT_ADDPOSITION(1,7,2800,0,"Stall 7")
// TT_ADDPOSITION(1,8,200,0,"Stall 8")
// TT_ADDPOSITION(1,9,3000,0,"Stall 9")



// DEFINE LEDS LATER
ALIAS(LED_TURNTABLE_POSITION_ENTRY, 408)
ALIAS(LED_TURNTABLE_POSITION_2    , 409)
ALIAS(LED_TURNTABLE_POSITION_3    , 410)
ALIAS(LED_TURNTABLE_POSITION_4    , 411)
ALIAS(LED_TURNTABLE_POSITION_5    , 412)
ALIAS(LED_TURNTABLE_POSITION_6    , 413)

CONFIGURE_SERVO(LED_TURNTABLE_POSITION_ENTRY  , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_TURNTABLE_POSITION_2      , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_TURNTABLE_POSITION_3      , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_TURNTABLE_POSITION_4      , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_TURNTABLE_POSITION_5      , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)
CONFIGURE_SERVO(LED_TURNTABLE_POSITION_6      , 4095, 0, PCA9685::NoPowerOff | PCA9685::Fast)


#ifndef ARDUINO_ARCH_ESP32
ROUTE(1,"Coal Yard exit")
  THROW(1)
  CLOSE(7)
DONE

ROUTE(2,"Coal Yard entry")
  THROW(1)
  CLOSE(7)
DONE

#define EX_TURNTABLE(route_id, reserve_id, vpin, steps, activity, desc) \
  ROUTE(route_id, desc) \
    RESERVE(reserve_id) \
    MOVETT(vpin, steps, activity) \
    WAITFOR(vpin) \
    FREE(reserve_id) \
    DONE
EX_TURNTABLE(TTRoute1, Turntable, 600, 114, Turn, "Position 1")
EX_TURNTABLE(TTRoute2, Turntable, 600, 227, Turn, "Position 2")
EX_TURNTABLE(TTRoute3, Turntable, 600, 341, Turn, "Position 3")

ALIAS(Turntable, 255)

// Turntable ROUTE ID reservations, using <? TTRouteX> for uniqueness:
ALIAS(TTRoute1)
ALIAS(TTRoute2)
ALIAS(TTRoute3)

SERVO_SIGNAL(101, 305, 280, 265)

ONGREEN(101)
  PRINT("Signal Green")
DONE

ONRED(101)
  PRINT("Signal Red")
DONE

#endif

#ifdef ARDUINO_ARCH_ESP32

ON_CROSSOVER_TURNOUT(POINT_FRONT_RIGHT_CROSSOVER, POINT_FRONT_RIGHT_CROSS_OUTER, POINT_FRONT_RIGHT_CROSS_INNER)
ON_CROSSOVER_TURNOUT(POINT_FRONT_LEFT_CROSSOVER, POINT_FRONT_LEFT_CROSS_OUTER, POINT_FRONT_LEFT_CROSS_INNER)
ON_CROSSOVER_TURNOUT(POINT_BACK_LEFT_CROSSOVER, POINT_BACK_LEFT_CROSS_OUTER, POINT_BACK_LEFT_CROSS_INNER)
ON_CROSSOVER_TURNOUT(POINT_BACK_RIGHT_CROSSOVER, POINT_BACK_RIGHT_CROSS_OUTER, POINT_BACK_RIGHT_CROSS_INNER)


ONTHROW(POINT_FRONT_RIGHT_REVERSE_LOOP)
  SET(LED_FRONT_RIGHT_REVERSE_LOOP)
  IFCLOSED(POINT_FRONT_RIGHT_CROSSOVER)
    RESET(LED_FRONT_RIGHT_CROSSOVER_INNER)
  ENDIF
DONE

ONCLOSE(POINT_FRONT_RIGHT_REVERSE_LOOP)
  RESET(LED_FRONT_RIGHT_REVERSE_LOOP)
  IFCLOSED(POINT_FRONT_RIGHT_CROSSOVER)
    SET(LED_FRONT_RIGHT_CROSSOVER_INNER)
  ENDIF
DONE

ON_TURNOUT_PAIR_LED(POINT_FRONT_RIGHT_LOOP, LED_FRONT_RIGHT_LOOP, LED_FRONT_RIGHT_LOOP_INNER)
ON_TURNOUT_PAIR_LED(POINT_ENGINE_SHED, LED_ENGINE, LED_ENGINE_YARD)
ON_TURNOUT_PAIR_LED(POINT_ENGINE_SHED_TO_TURNTABLE, LED_ENGINE_SHED_SIDING, LED_TO_TURNTABLE)
ON_TURNOUT_PAIR_LED(POINT_YARD, LED_YARD, LED_RIGHT_LOOP)
ON_TURNOUT_PAIR_LED(POINT_GOODS_OR_PASSENGER, LED_PASSENGER, LED_GOODS)


ON_TURNOUT_PAIR_LED(POINT_PASSENGER_SIDINGS, LED_PASSENGER_BACK, LED_PASSENGER_FRONT)
ON_TURNOUT_PAIR_LED(POINT_GOODS_SHED, LED_GOODS_OR_GOODS_SHED_SHED, LED_GOODS_OR_GOODS_SHED_GOODS)
ON_TURNOUT_PAIR_LED(POINT_GOODS_SIDINGS, LED_GOODS_BACK, LED_GOODS_FRONT)
ON_TURNOUT_PAIR_LED(POINT_BACK_LEFT_REVERSE_LOOP, LED_REAR_REVERSE_LOOP_THROWN, LED_REAR_REVERSE_LOOP_CLOSED)

ONTHROW(POINT_FRONT_RIGHT_CROSSOVER)
  SET(LED_FRONT_RIGHT_CROSSOVER_CROSSED)
  RESET(LED_FRONT_RIGHT_CROSSOVER_INNER)
  RESET(LED_FRONT_RIGHT_CROSSOVER_OUTER)
DONE

ONCLOSE(POINT_FRONT_RIGHT_CROSSOVER)
  RESET(LED_FRONT_RIGHT_CROSSOVER_CROSSED)
  IFCLOSED(POINT_FRONT_RIGHT_REVERSE_LOOP)
    SET(LED_FRONT_RIGHT_CROSSOVER_INNER)
  ENDIF
  SET(LED_FRONT_RIGHT_CROSSOVER_OUTER)
DONE


ON_CROSSOVER_LED(POINT_BACK_LEFT_CROSSOVER, LED_BACK_LEFT_CROSSOVER_OUTER, LED_BACK_LEFT_CROSSOVER_CROSSED, LED_BACK_LEFT_CROSSOVER_INNER)
ON_CROSSOVER_LED(POINT_BACK_RIGHT_CROSSOVER, LED_BACK_RIGHT_CROSSOVER_OUTER, LED_BACK_RIGHT_CROSSOVER_CROSSED, LED_BACK_RIGHT_CROSSOVER_INNER)


ONTHROW(POINT_FRONT_LEFT_CROSSOVER)
  RESET(LED_FRONT_LEFT_CROSSOVER_OUTER)
  SET(LED_FRONT_LEFT_CROSSOVER_CROSSED)
  RESET(LED_FRONT_LEFT_CROSSOVER_INNER)
DONE

ONCLOSE(POINT_FRONT_LEFT_CROSSOVER)
  SET(LED_FRONT_LEFT_CROSSOVER_OUTER)
  RESET(LED_FRONT_LEFT_CROSSOVER_CROSSED)
  IFCLOSED(POINT_FRONT_LEFT_LOOP)
    SET(LED_FRONT_LEFT_CROSSOVER_INNER)
  ENDIF
DONE

ONTHROW(POINT_FRONT_LEFT_LOOP)
  SET(LED_FRONT_LEFT_LOOP)
  RESET(LED_FRONT_LEFT_CROSSOVER_INNER)
DONE

ONCLOSE(POINT_FRONT_LEFT_LOOP)
  RESET(LED_FRONT_LEFT_LOOP)
  IFCLOSED(POINT_FRONT_LEFT_CROSSOVER)
    SET(LED_FRONT_LEFT_CROSSOVER_INNER)
  ENDIF
DONE

// UNCOUPLERS

ON_UNCOUPLER_LED(UNCOUPLER_FRONT_RIGHT_OUTER, LED_UNCOUPLE_FRONT_RIGHT_OUTER)
ON_UNCOUPLER_LED(UNCOUPLER_FRONT_RIGHT_INNER, LED_UNCOUPLE_FRONT_RIGHT_INNER)
ON_UNCOUPLER_LED(UNCOUPLER_FRONT_RIGHT_LOOP, LED_UNCOUPLE_FRONT_RIGHT_LOOP)
ON_UNCOUPLER_LED(UNCOUPLER_FRONT_LEFT_OUTER, LED_UNCOUPLE_FRONT_LEFT_OUTER)
ON_UNCOUPLER_LED(UNCOUPLER_FRONT_LEFT_INNER, LED_UNCOUPLE_FRONT_LEFT_INNER)
ON_UNCOUPLER_LED(UNCOUPLER_FRONT_LEFT_LOOP, LED_UNCOUPLE_FRONT_LEFT_LOOP)
ON_UNCOUPLER_LED(UNCOUPLER_PASSENGER_REAR, LED_UNCOUPLE_PASSENGER_BACK)
ON_UNCOUPLER_LED(UNCOUPLER_PASSENGER_FRONT, LED_UNCOUPLE_PASSENGER_FRONT)
ON_UNCOUPLER_LED(UNCOUPLER_GOODS_SHED, LED_UNCOUPLE_GOODS_SHED)
ON_UNCOUPLER_LED(UNCOUPLER_GOODS_BACK, LED_UNCOUPLE_GOODS_BACK)
ON_UNCOUPLER_LED(UNCOUPLER_GOODS_FRONT, LED_UNCOUPLE_GOODS_FRONT)

// Kill!!
ONBUTTON(BUTTON_KILL)
  ESTOPALL
DONE

// back left crossover
ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_BACK_LEFT_CROSSOVER, POINT_BACK_LEFT_CROSSOVER)

// back left reverse loop
ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_BACK_LEFT_REVERSE_LOOP, POINT_BACK_LEFT_REVERSE_LOOP)

// goods sidings
ON_BUTTON_TOGGLE_TURNOUT(BUTTON_BACK_LEFT_GOODS_SIDINGS, POINT_GOODS_SIDINGS)

// front left loop
ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_FRONT_LEFT_LOOP, POINT_FRONT_LEFT_LOOP)

// front left crossover
ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_FRONT_LEFT_CROSSOVER, POINT_FRONT_LEFT_CROSSOVER)


// goods shed
ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_GOODS_SHED, POINT_GOODS_SHED)


// passenger sidings
ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_PASSENGER_SIDINGS, POINT_PASSENGER_SIDINGS)


ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_GOODS_OR_PASSENGER, POINT_GOODS_OR_PASSENGER)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_YARD, POINT_YARD)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_ENGINE_SHED, POINT_ENGINE_SHED)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_FRONT_RIGHT_LOOP, POINT_FRONT_RIGHT_LOOP)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_FRONT_RIGHT_CROSSOVER, POINT_FRONT_RIGHT_CROSSOVER)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_FRONT_RIGHT_REVERSE_LOOP, POINT_FRONT_RIGHT_REVERSE_LOOP)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_BACK_RIGHT_CROSSOVER, POINT_BACK_RIGHT_CROSSOVER)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_POINT_TO_TURNTABLE, POINT_ENGINE_SHED_TO_TURNTABLE)


// UNCOUPLERS

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_UNCOUPLE_OUTER_RIGHT, UNCOUPLER_FRONT_RIGHT_OUTER)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_UNCOUPLE_INNER_RIGHT, UNCOUPLER_FRONT_RIGHT_INNER)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_UNCOUPLE_RIGHT_LOOP, UNCOUPLER_FRONT_RIGHT_LOOP)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_UNCOUPLE_OUTER_LEFT, UNCOUPLER_FRONT_LEFT_OUTER)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_UNCOUPLE_INNER_LEFT, UNCOUPLER_FRONT_LEFT_INNER)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_UNCOUPLE_LEFT_LOOP, UNCOUPLER_FRONT_LEFT_LOOP)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_UNCOUPLE_REAR_PASSENGER, UNCOUPLER_PASSENGER_REAR)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_UNCOUPLE_FRONT_PASSENGER, UNCOUPLER_PASSENGER_FRONT)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_UNCOUPLE_GOODS_SHED, UNCOUPLER_GOODS_SHED)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_UNCOUPLE_BACK_SIDING, UNCOUPLER_GOODS_BACK)

ON_BUTTON_TOGGLE_TURNOUT(BUTTON_UNCOUPLE_FRONT_SIDING, UNCOUPLER_GOODS_FRONT)

// TURNTABLE

SEQUENCE(TURNTABLE_LEDS_OFF)
  RESET(LED_TURNTABLE_POSITION_ENTRY)
  RESET(LED_TURNTABLE_POSITION_2)
  RESET(LED_TURNTABLE_POSITION_3)
  RESET(LED_TURNTABLE_POSITION_4)
  RESET(LED_TURNTABLE_POSITION_5)
  RESET(LED_TURNTABLE_POSITION_6)
  RETURN
DONE

ON_TURNTABLE_BUTTON(BUTTON_TURNTABLE_ENTRY, TURNTABLE_ID_1, TURNTABLE_POSITION_ENTRY, TURNTABLE_POSITION_REVERSE_ENTRY, LED_TURNTABLE_POSITION_ENTRY)
ON_TURNTABLE_BUTTON(BUTTON_TURNTABLE_3, TURNTABLE_ID_1, TURNTABLE_POSITION_3, TURNTABLE_POSITION_REVERSE_3, LED_TURNTABLE_POSITION_3)
ON_TURNTABLE_BUTTON(BUTTON_TURNTABLE_4, TURNTABLE_ID_1, TURNTABLE_POSITION_4, TURNTABLE_POSITION_REVERSE_4, LED_TURNTABLE_POSITION_4)
ON_TURNTABLE_BUTTON(BUTTON_TURNTABLE_5, TURNTABLE_ID_1, TURNTABLE_POSITION_5, TURNTABLE_POSITION_REVERSE_5, LED_TURNTABLE_POSITION_5)
ON_TURNTABLE_BUTTON(BUTTON_TURNTABLE_6, TURNTABLE_ID_1, TURNTABLE_POSITION_6, TURNTABLE_POSITION_REVERSE_6, LED_TURNTABLE_POSITION_6)


// sensors
ON_SENSOR_LED(-SENSOR_OCCUPIED_RIGHT_OUTER_CURVE, LED_OCCUPIED_RIGHT_CURVE_OUTER)
ON_SENSOR_LED(-SENSOR_OCCUPIED_RIGHT_INNER_CURVE, LED_OCCUPIED_RIGHT_CURVE_INNER)
ON_SENSOR_LED(-SENSOR_OCCUPIED_REVERSE_LOOP, LED_OCCUPIED_REVERSE_LOOP)

ON_SENSOR_PAIR_LED(-SENSOR_OCCUPIED_FRONT_OUTER_LEFT, -SENSOR_OCCUPIED_FRONT_OUTER_RIGHT, LED_OCCUPIED_FRONT_OUTER)

ON_SENSOR_PAIR_LED(-SENSOR_OCCUPIED_FRONT_OUTER_RIGHT, -SENSOR_OCCUPIED_FRONT_OUTER_LEFT, LED_OCCUPIED_FRONT_OUTER)
ON_SENSOR_PAIR_LED(-SENSOR_OCCUPIED_FRONT_INNER_LEFT, -SENSOR_OCCUPIED_FRONT_INNER_RIGHT, LED_OCCUPIED_FRONT_INNER)
ON_SENSOR_PAIR_LED(-SENSOR_OCCUPIED_FRONT_INNER_RIGHT, -SENSOR_OCCUPIED_FRONT_INNER_LEFT, LED_OCCUPIED_FRONT_INNER)
ON_SENSOR_PAIR_LED(-SENSOR_OCCUPIED_LOOP_1, -SENSOR_OCCUPIED_LOOP_2, LED_OCCUPIED_LOOP)
ON_SENSOR_PAIR_LED(-SENSOR_OCCUPIED_LOOP_2, -SENSOR_OCCUPIED_LOOP_1, LED_OCCUPIED_LOOP)

ON_SENSOR_LED(-SENSOR_OCCUPIED_REAR_OUTER_LEFT, LED_OCCUPIED_REAR_OUTER_LEFT)
ON_SENSOR_LED(-SENSOR_OCCUPIED_REAR_INNER_LEFT, LED_OCCUPIED_REAR_INNER_LEFT)
ON_SENSOR_LED(-SENSOR_OCCUPIED_REAR_OUTER_RIGHT, LED_OCCUPIED_REAR_OUTER_RIGHT)
ON_SENSOR_LED(-SENSOR_OCCUPIED_REAR_INNER_RIGHT, LED_OCCUPIED_REAR_INNER_RIGHT)
ON_SENSOR_LED(-SENSOR_OCCUPIED_YARD, LED_OCCUPIED_YARD)
ON_SENSOR_LED(-SENSOR_OCCUPIED_LEFT_OUTER_CURVE, LED_OCCUPIED_LEFT_CURVE_OUTER)
ON_SENSOR_LED(-SENSOR_OCCUPIED_LEFT_INNER_CURVE, LED_OCCUPIED_LEFT_CURVE_INNER)

SEQUENCE(SEQUENCE_STARTUP)
  SET(LED_FRONT_RIGHT_CROSSOVER_INNER)
  SET(LED_FRONT_RIGHT_CROSSOVER_OUTER)
  SET(LED_FRONT_RIGHT_LOOP_INNER)
  SET(LED_ENGINE_YARD)
  SET(LED_TO_TURNTABLE)
  SET(LED_RIGHT_LOOP)
  SET(LED_GOODS)
  SET(LED_GOODS_OR_GOODS_SHED_GOODS)
  SET(LED_GOODS_FRONT)
  SET(LED_PASSENGER_FRONT)

  SET(LED_REAR_REVERSE_LOOP_CLOSED)
  SET(LED_BACK_LEFT_CROSSOVER_OUTER)
  SET(LED_BACK_LEFT_CROSSOVER_INNER)
  SET(LED_FRONT_LEFT_CROSSOVER_OUTER)
  SET(LED_FRONT_LEFT_CROSSOVER_INNER)

  SET(LED_BACK_RIGHT_CROSSOVER_INNER)
  SET(LED_BACK_RIGHT_CROSSOVER_OUTER)

  POWERON
DONE

#endif