name: Clang Format PR Suggestions

on:
  pull_request:
    branches: [master]

jobs:
  clang-format-suggest:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # full history is needed for diff

      - name: Install clang-format and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-15 python3-pip
          sudo ln -sf /usr/bin/clang-format-15 /usr/local/bin/clang-format
          pip3 install requests

      - name: Download reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
  
      - name: Run clang-format with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin master
          git diff -U0 origin/master...HEAD > pr.diff
          clang-format-diff.py -p1 -style=file < pr.diff \
            | reviewdog -f=diff -name="clang-format" -reporter=github-pr-review -level=info
